name: Terraform Azure Deployment

on:
  push:
    branches:
      - main   # sirf main branch par apply chalega
  pull_request:

jobs:
  terraform:
    runs-on: dhondhu-maharaj-2

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Azure Login using GitHub Secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6   # apne version ke hisaab se update kar lena

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Terraform Apply (sirf main branch par chalega)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
